# Number of days of inactivity before an issue becomes stale
daysUntilStale: 21
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - todo
  - 'in progress'
  - 'needs review'
  - 'high priority'
  - 'good first issue'

# Label to use when marking an issue as stale
staleLabel: inactive
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi everyone! Seems like there hasn't been much going on in this issue lately.
  If there are still questions, comments, or bugs, please feel free to continue
  the discussion. Unfortunately, we don't have time to get to every issue. We
  are always open to contributions so please send us a pull request if you would
  like to help. Inactive issues will be closed after 30 days. Thanks!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Hey there, it's me again! I am going close this issue to help our maintainers
  focus on the current development roadmap instead. If the issue mentioned is
  still a concern, please open a new ticket and mention this old one. Cheers
  and thanks for using Open Web Components!
