name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'open-wc/open-wc'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build types
        run: yarn types

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
